from flask import Flask, render_template, request, jsonify, send_file
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
import datetime
import os

app = Flask(__name__)

# -----------------------------
# GLOBAL STORAGE (IMPORTANT FIX)
# -----------------------------
last_report = {}

# -----------------------------
# HOME
# -----------------------------
@app.route("/")
def index():
    return render_template("index.html")

# -----------------------------
# CHAT API (TEXT + VOICE)
# -----------------------------
@app.route("/chat", methods=["POST"])
def chat():
    global last_report

    user_message = request.json.get("message", "").lower()

    disease = "General Health Issue"
    advice = "Please consult a doctor for accurate diagnosis."
    emergency = False

    if "fever" in user_message and "cold" in user_message:
        disease = "Common Viral Infection"
        advice = "Take rest, drink warm fluids, and monitor temperature."

    elif "chest pain" in user_message or "breathing" in user_message:
        disease = "Possible Cardiac or Respiratory Issue"
        advice = "Seek medical attention immediately."
        emergency = True

    elif "headache" in user_message:
        disease = "Migraine or Stress Headache"
        advice = "Rest in a quiet place and stay hydrated."

    elif "stomach pain" in user_message:
        disease = "Gastric or Digestive Issue"
        advice = "Avoid spicy food and drink plenty of water."

    reply = f"Based on your symptoms, you may have {disease}. {advice}"

    # ✅ STORE REPORT DATA (FIX)
    last_report = {
        "symptoms": user_message,
        "disease": disease,
        "advice": advice,
        "date": datetime.datetime.now().strftime("%d-%m-%Y %H:%M")
    }

    return jsonify({
        "reply": reply,
        "emergency": emergency
    })

# -----------------------------
# PDF DOWNLOAD
# -----------------------------
@app.route("/download_report")
def download_report():
    global last_report

    if not last_report:
        return "No report available. Please check symptoms first."

    file_name = "Health_Report.pdf"
    file_path = os.path.join(os.getcwd(), file_name)

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    content = []

    content.append(Paragraph("<b>AI Health Assistant - Medical Report</b>", styles["Title"]))
    content.append(Paragraph(f"<b>Date:</b> {last_report['date']}", styles["Normal"]))
    content.append(Paragraph("<br/>", styles["Normal"]))

    content.append(Paragraph(f"<b>Symptoms:</b> {last_report['symptoms']}", styles["Normal"]))
    content.append(Paragraph(f"<b>Predicted Condition:</b> {last_report['disease']}", styles["Normal"]))
    content.append(Paragraph(f"<b>Advice:</b> {last_report['advice']}", styles["Normal"]))

    content.append(Paragraph("<br/><br/>⚠ This report is generated by AI. Please consult a doctor.", styles["Italic"]))

    doc.build(content)

    return send_file(file_path, as_attachment=True)

# -----------------------------
# RUN
# -----------------------------
if __name__ == "__main__":
    app.run(debug=True)
